In [23]:
import sys
sys.path.append('../src')

%load_ext autoreload
%autoreload 2

import numpy as np
from equation.burgers import Burgers1D, InitialCondition, BoundaryCondition
import torch
from equation.derivative import diff

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [24]:
eq = Burgers1D(nu=1)
ic = InitialCondition()
bc = BoundaryCondition()

In [25]:
x = np.ones((10,))*2
t = np.ones((10,))

x = torch.tensor(x, dtype=torch.float32)
t = torch.tensor(t, dtype=torch.float32)

x.requires_grad, t.requires_grad = True, True

In [26]:
print(x.grad, t.grad)

None None


In [27]:
u = {}
u["interior"] = x**2 + t**2
u["boundary"] = x**2 + t**2
u["initial"] = x**2 + t**2

In [28]:
eq.residual(u, t, x)

tensor([20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       grad_fn=<SubBackward0>)

In [29]:
ic.residual(u, t, x)

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.], grad_fn=<SubBackward0>)

In [30]:
bc.residual(u, t, x)

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.], grad_fn=<SubBackward0>)

In [31]:
eq.loss(u, t, x)

tensor(400., grad_fn=<MeanBackward0>)

In [32]:
bc.loss(u, t, x)

tensor(25., grad_fn=<MeanBackward0>)